services:
  my-airflow-container:
    image: apache/airflow:2.7.3-python3.11
    container_name: my-airflow-container
    restart: always
    environment:
      - AIRFLOW__CORE__EXECUTOR=SequentialExecutor
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=sqlite:////opt/airflow/airflow.db  # ◀ CORE에서 DATABASE로 변경
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
      - AIRFLOW__WEBSERVER__SECRET_KEY=my_super_secret_key_12345
    logging:
      options:
        max-size: "10m"
        max-file: "3"
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins
      - ../:/opt/de-roadmap
      - airflow-db-volume:/opt/airflow  # ◀ 기존 설정을 '도커 볼륨 이름'으로 변경

    ports:
      - "8089:8080"
    command: bash -c "airflow db init && (airflow scheduler & airflow webserver)"

# ◀ 파일의 가장 마지막 줄(맨 밑바닥)에 아래 내용을 똑같이 추가해 줍니다.
volumes:
  airflow-db-volume:
